export const allowedOfficerRoles = [
  "Street Maintenance Operator",
  "Public Lighting Operator",
  "Waste Management Operator",
  "Urban Mobility Operator",
  "Green Spaces Operator",
  "Water Infrastructure Operator",
  "Accessibility Officer",
  "Environmental Surveillance Officer",
  "Road Safety Inspector",
  "Public Lighting Technician",
  "Urban Mobility Planner",
  "Green Maintenance Technician",
  "Water Quality Inspector",
  "Accessibility Inspector",
  "Digital Services Technician",
  "Emergency Response Liaison",
  "Noise and Air Quality Technician",
  "External Maintainer"
];
